networks:
  default:
    name: "${NETWORK_ID}"
    external: false

services:
  nginx:
    image: nginx:1.26
    restart: unless-stopped
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - traefik
    volumes:
    - ./:/usr/share/nginx/html:ro

    ## Alternative for macOS users: Mutagen https://wodby.com/docs/stacks/laravel/local#docker-for-mac
    #    - backend:/var/www/html
    labels:
    - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"
    - "traefik.http.routers.${PROJECT_NAME}_nginx.entrypoints=websecure"
    - "traefik.http.routers.${PROJECT_NAME}_nginx.tls=true"



  traefik:
    image: traefik:v2.0
    restart: unless-stopped
    container_name: "${PROJECT_NAME}_traefik"
    command: --api.insecure=true --providers.docker --entryPoints.websecure.address=:443
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock